-- Create messages table for Contact Form
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  read boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;

-- Create policy to allow anyone to insert (send) messages
create policy "Anyone can insert messages"
on public.messages for insert
with check (true);

-- Create policy to allow admins (authenticated users) to view/update/delete messages
-- Note: You might want to restrict this further to specific admin roles if you have them
create policy "Authenticated users can view messages"
on public.messages for select
to authenticated
using (true);

create policy "Authenticated users can update messages"
on public.messages for update
to authenticated
using (true);

create policy "Authenticated users can delete messages"
on public.messages for delete
to authenticated
using (true);


-- Add media column to impacts table (JSON array of URLs)
-- alter table public.impacts add column media jsonb default '[]'::jsonb;

-- Create site_content table for CMS
create table public.site_content (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  key text not null unique,
  value text
);

-- Enable RLS
alter table public.site_content enable row level security;

-- Allow anyone to read content
create policy "Anyone can read site content"
on public.site_content for select
using (true);

-- Allow admins to update content
create policy "Authenticated users can update site content"
on public.site_content for update
to authenticated
using (true);

create policy "Authenticated users can insert site content"
on public.site_content for insert
to authenticated
with check (true);

-- Insert initial About Us content
insert into public.site_content (key, value)
values ('about_us', 'To empower vulnerable communities in Afghanistan through sustainable humanitarian assistance and development programs. We believe in transparency, accountability, and creating lasting positive change.');
